//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace closing_store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_service
    {
        public int id { get; set; }
        public string complain { get; set; }
        public Nullable<int> staff_id { get; set; }
    
        public virtual staff staff { get; set; }
    }
}
