//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace closing_store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class getallorders2
    {
        public int id { get; set; }
        public string customer { get; set; }
        public string phone { get; set; }
        public string Address { get; set; }
        public string product_name { get; set; }
        public Nullable<int> pro_price { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> order_total { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
