//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace closing_store.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Closing_storeEntities : DbContext
    {
        public Closing_storeEntities()
            : base("name=Closing_storeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<customer_address> customer_address { get; set; }
        public virtual DbSet<customer_buy_product> customer_buy_product { get; set; }
        public virtual DbSet<customer_service> customer_service { get; set; }
        public virtual DbSet<deliver> delivers { get; set; }
        public virtual DbSet<delivers_location> delivers_location { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<review> reviews { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<sales_history> sales_history { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<transactions_items> transactions_items { get; set; }
        public virtual DbSet<visa> visas { get; set; }
        public virtual DbSet<getallorders2> getallorders2 { get; set; }
    }
}
