//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace closing_store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int order_id { get; set; }
        public string pro_name { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<int> transaction_id { get; set; }
        public Nullable<int> pro_id { get; set; }
        public Nullable<int> pro_price { get; set; }
        public Nullable<int> order_total { get; set; }
    
        public virtual transaction transaction { get; set; }
    }
}
